services:
  tests:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install tox && tox"

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  play-game:
    build:
      context: .
    # environment: # Uncomment if you want to see logs from DEBUG level
      # LOG_LEVEL: "DEBUG" # Uncomment if you want to see logs from DEBUG level
    depends_on:
      - db
    command: >
      python main.py