"""empty message

Revision ID: 0de072625b02
Revises: bd165b5ce344
Create Date: 2021-04-03 20:37:39.696440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de072625b02'
down_revision = 'bd165b5ce344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
